### ISSUE TITLE
isEven() method is not effective

### ISSUE THREAD

**Issue by synthMoza** [OborotovMikhail/LongNumberLib#1]
https://github.com/OborotovMikhail/LongNumberLib/blob/02e081c857f6ecc8142d0078160071741273e8c8/include/LongNumberLib.h#L176-L185

Не проще ли просто взять остаток по модуля два от последней цифры? Кстати, явный this здесь непонятно зачем, его можно опустить.
```
bool LongInt::isEven() { 
 	return (_digits[0] % 2 == 0);
 } 
```

**Comment by mikeoborotov** [comment]
Да, разумеется проще)
Будет исправлено
