### ISSUE TITLE
Implement operator overload instead of C-like functions

### ISSUE THREAD

**Issue by synthMoza** [OborotovMikhail/LongNumberLib#2]
https://github.com/OborotovMikhail/LongNumberLib/blob/02e081c857f6ecc8142d0078160071741273e8c8/include/LongNumberLib.h#L259-L345

Почему бы вместо этих функция не перегрузить операторы +, =, <, > и т.д.? Так будет намного удобнее использовать, и это более походит на плюсовую библиотеку, нежели сишную:
```
LongInt a{"123"}, b{"321"};
LongInt c = a + b;
if (a <= b)
    a = a + b;
```

**Comment by mikeoborotov** [comment]
В финальной версии библиотеки изначально планировалась перегрузка всех операторов, все это будет.
Просто у самого есть привычка пользоваться функциями, поэтому пока начал писать реализацию в таком виде.
Пока что планируется, что будут и функции и перегруженные операторы, просто для небольшой избыточности библиотеки (возможно кому то так будет удобнее).
